name: reacthome_vision
publish_to: none

environment:
  sdk: ^3.9.0

workspace:
  - apps/flow/android
  - apps/flow/ios
  - apps/flow/linux
  - apps/flow/macos
  - apps/flow/windows
  - apps/lab/android
  - apps/lab/ios
  - apps/lab/linux
  - apps/lab/macos
  - apps/lab/windows
  - apps/studio/linux
  - apps/studio/macos
  - apps/studio/windows
  - packages/apps/flow
  - packages/apps/lab
  - packages/apps/studio
  - packages/assets
  - packages/common
  - packages/vision

dependency_overrides:
  glue:
    git:
      url: https://github.com/gev/glue.git
      path: dart/glue

  glue_flutter:
    git:
      url: https://github.com/gev/glue.git
      path: flutter/glue_flutter
